version: "3.7"
services:
  db:
    build: ./sql
    image: bs12-db:latest
    networks:
      - internal
    volumes:
      - "./sql/test_db:/var/lib/mysql"
  game:
    build:
      context: .
      target: spacestation
    image: bs12:latest
    depends_on:
      - db
    networks:
      - internal
    ports:
      - "8000:8000"
networks:
  internal: